#!/bin/sh
### BEGIN INIT INFO
# Provides:          xfdd
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: xfd for jenkins
### END INIT INFO

RETVAL=0

usage ()
{
	echo $"Usage: $0 {start|stop|restart|reload}" 1>&2
	RETVAL=2
}
	
start ()
{
	[ -f /usr/local/bin/xfdd ] || exit 6
	/usr/local/bin/xfdd
}

restart ()
{
	start
}


case "$1" in
    stop) kill `ps -C xfdd -o pid=` > /dev/null ;;
    status) status ;;
    start|restart|reload) restart ;;
    *) usage ;;
esac

exit $RETVAL
