#!/bin/sh
### BEGIN INIT INFO
# Provides:          xfd
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: xfd
### END INIT INFO

RETVAL=0

usage ()
{
	echo $"Usage: $0 {start|stop|restart|reload}" 1>&2
	RETVAL=2
}
	
start ()
{
	[ -f /usr/local/bin/xfd ] || exit 6
	/usr/local/bin/xfd
}

restart ()
{
	start
}


case "$1" in
    stop) kill `ps -C xfd -o pid=` > /dev/null ;;
    status) status ;;
    start|restart|reload) restart ;;
    *) usage ;;
esac

exit $RETVAL
#!/bin/sh
### BEGIN INIT INFO
# Provides:          triggerhappy
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: triggerhappy hotkey daemon
### END INIT INFO

# Author: Stefan Tomanek <stefan.tomanek+th@wertarbyte.de>
